### ISSUE TITLE
Additional project?

### ISSUE THREAD

**Issue by rtgoodwin** [LelandSindt/teslacam#1]
Hi @LelandSindt ! Very cool stuff, some great takes on protecting the storage. 

We have another similar project going at https://github.com/cimryan/teslausb and would be curious if you think it might be a good idea to collaborate. We have a [Slack](https://join.slack.com/t/smartusbdrivefortesla/shared_invite/enQtNDY4NDIzMTQ0NjA4LTdlYjFkOGE0Y2NkNjYyZTBiZTNmZTY4OGNhODMwZjg4NGNkZWU3MGY2ZDNhODIzZTAxODhhNzEzNDQ2OTFhMTI) going also if you'd like to join to discuss. 

Great work!

**Comment by LelandSindt** [comment]
@rtgoodwin thanks for reaching out, and for the kind words. 

As time allows I will have a look at the teslausb project/slack.
