### ISSUE TITLE
does it still work with 2019.5.x

### ISSUE THREAD

**Issue by rounders** [LelandSindt/teslacam#3]
I've been playing around with mounting my Pi to my Tesla and I was able to get it working using a similar technique to how you are doing it but since updating to 2019.5.x it doesn't work. My Tesla just shows a little greyed out camera icon with an 'X' next to it.  

@LelandSindt Have you successfully tested your solution with 2019.5.x ?

**Comment by LelandSindt** [comment]
Unfortunately, I am still running 2018.50.6

That's said I didn't expect any incompatibility.

I will certainly address any issues I find when I get the chance.

Thank you.

**Comment by rounders** [comment]
@LelandSindt found another thread on another repo that is relevant to this: https://github.com/cimryan/teslausb/issues/119#issuecomment-471342299  
I tried out the suggested solution and if did indeed fix it.

**Comment by LelandSindt** [comment]
@rounders thanks I will check this out when I get back into town.

🛳️

**Comment by LelandSindt** [comment]
@rounders thanks again, Everything is updated to work with/support 2019.5.x
