### ISSUE TITLE
Issue with deleting empty dirs

### ISSUE THREAD

**Issue by th3fallen** [LelandSindt/teslacam#4]
In service.sh you have `find /data/TeslaCam -type d -empty -delete` with the intention of deleting empty child folders but in fact it is deleting the `/data/TeslaCam` directory which is breaking the rest of the script from running.

**Comment by th3fallen** [comment]
i fixed it for myself by doing... `find /data/TeslaCam -type d \( ! -name TeslaCam \) -empty -delete`
Hope this helps

**Comment by LelandSindt** [comment]
Thank you.. If you want to clone/issue a pull request I will accept... If not I will make the change soon.
